services:
  counters:
    build: ../
    container_name: telemetry-counters-api
    env_file:
      - .env
    environment:
      - MODE=COUNTERS
    ports:
      - "9001:9001"
    networks:
      - default
  localstack:
    image: localstack/localstack:3
    container_name: localstack
    env_file:
      - .env
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/localstack-init.sh
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:14-alpine
    container_name: telemetry-aggregation-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    networks:
      default:
        aliases:
          - db
          - telemetry-db

  api:
    build: ../
    container_name: telemetry-aggregation-api
    depends_on:
      - db
      - localstack
      - counters
    env_file:
      - .env
    environment:
      - MODE=API
      - DATABASE_URL=postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@telemetry-aggregation-db:5432/$POSTGRES_DB
    ports:
      - "8080:8080"
    networks:
      - default

  worker:
    build: ../
    container_name: telemetry-aggregation-worker
    depends_on:
      - db
      - localstack
      - counters
    env_file:
      - .env
    environment:
      - MODE=WORKER
    networks:
      - default

networks:
  default: