services:
  telemetry-aggregation-db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    networks:
      default:
        aliases:
          - db
          - telemetry-db

  api:
    build: ../
    depends_on:
      - telemetry-aggregation-db
    env_file:
      - .env
    environment:
      - MODE=API
      - DATABASE_URL=postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@telemetry-aggregation-db:5432/$POSTGRES_DB
    ports:
      - "8080:8080"
    networks:
      - default

#  worker:
#    build: .
#    depends_on:
#      - telemetry-aggregation-db
#    env_file:
#      - .env
#    environment:
#      - MODE=WORKER
#      - DATABASE_URL=postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@telemetry-aggregation-db:5432/$POSTGRES_DB
#    networks:
#      - default

networks:
  default: